name: Release

on:
  push:
    branches:
      [main]

jobs:
  generate_sentry_release:
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Split Repo Name
        uses: jungwinter/split@v2
        id: split_repo_name
        with:
          msg: ${{ github.repository }}
          seperator: "/"
          maxsplit: 1
      - name: Echo Repo Name
        run: echo "${{steps.split_repo_name.outputs._1}}"
      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: "test version"
          sourcemaps: "./dist"
          url_prefix: "~"
      